### ISSUE TITLE
Update future jobs periodically.

### ISSUE THREAD

**Issue by AlexAndHisScripts** [wose/satnogs-monitor#20]
Or increase the rate/make it a parameter if it's already there, I tried to look for it but I'm not good with rust's syntax.

**Comment by wose** [comment]
Hi,

jobs are updated every 10 minutes. This guarantees to get the observation info before the observation starts as you can't schedule observations sooner than now + 10 minutes. I'd like to keep this as default since it creates the least api calls without missing observations, but I'll add a parameter so you can overwrite it.
